- name: Copy Ansible Logo
  copy:
    src: webpage_logo.png
    dest: /var/www/html/
  become: yes

- name: Copy CSS
  copy:
    src: css
    dest: /var/www/html/
  become: yes

- name: create HTML report
  template:
    src: report.j2
    dest: /var/www/html/index.html
  become: yes
  notify: restart_apache

- name: update directory permissions
  file`:
    path: /var/www/html
    recurse: yes
    mode: '0755'
  become: yes
  notify: restart_apache
