---
- name: Add RHEL8 users from data file
  hosts: ec2
  gather_facts: yes
  vars_files:
    - ./vars/linux_users.yml
    - ./vars/default-vars.yml

  tasks:

    - block:
      #Create users and force them to change password upon first login
      #https://lebenplusplus.de/2017/04/19/creating-users-and-their-passwords-with-ansible/
      - name: Add users
        user:
          name: "{{ item.username }}"
          groups: wheel
        with_items: "{{ linux_users }}"
        become: yes

      - name: Add public ssh key to user
        authorized_key:
          user: "{{ item.username }}"
          state: present
          key: "{{ lookup('file', '{{ working_dir }}/{{ ec2_prefix }}-key.pub') }}"
        with_items: "{{ linux_users }}"
        become: yes

      - name: Unlock password and set it to empty
        command: "passwd -d {{ item.username }}"
        with_items: "{{ linux_users }}"
        become: yes

      - name: Expire password
        command: "chage -d 0 {{ item.username }}"
        with_items: "{{ linux_users }}"
        become: yes

      - name: Allow newly added users to sudo without a password
        template:
          src: ./templates/sudoers.j2
          dest: /etc/sudoers.d/sudoers
          validate: 'visudo -cf %s'
          mode: 0440
        become: yes
      when: ec2_tag_group == "rhel"
