#https://github.com/ansible-collections/community.kubernetes
---
- name: deploy Jenkins with Helm
  hosts: localhost
  gather_facts: no
  vars_files:
    - ./vars/default-vars.yml

  tasks:

    # - name: Grab hashicorp repository
    #   community.kubernetes.helm_repository:
    #     repo_name: hashicorp
    #     repo_url: https://helm.releases.hashicorp.com
    #     state: present

    # - name: Create helm namespace as HELM 3 doesn't create it automatically
    #   community.kubernetes.k8s:
    #     kubeconfig: "{{ working_dir }}/{{gcp_prefix}}-config"
    #     state: present
    #     api_version: v1
    #     kind: Namespace
    #     name: "jenkins"
    #     wait: true

    # - name: Deploy consul with helm
    #   community.kubernetes.helm:
    #     kubeconfig_path: "{{ working_dir }}/{{gcp_prefix}}-config"
    #     name: consul
    #     chart_ref: hashicorp/consul
    #     release_namespace: hashicorp
    #     # state: absent
    #     wait: true
    #     values:
    #       global:
    #         datacenter: vault-kubernetes-guide
    #       client:
    #         enabled: true
    #       server:
    #         replicas: 1
    #         bootstrapExpect: 1
    #         disruptionBudget:
    #           maxUnavailable: 0

    - name: Deploy Jenkins with Helm
      community.kubernetes.helm:
        kubeconfig_path: "{{ working_dir }}/{{gcp_prefix}}-config"
        release_name: my-release
        chart_ref: stable/jenkins
        create_namespace: yes
        release_namespace: jenkins
        # state: absent
        wait: true
        values: "{{ lookup('template', 'vars/helm_values/jenkins.yml')}}"
