#How to install docker CE in RHEL8
#https://linuxconfig.org/how-to-install-docker-in-rhel-8
---
- name: Ensure Docker Engine is installed on webserver
  hosts: ec2
  gather_facts: no
  vars_files:
    - ./vars/default-vars.yml
    - ./credentials/redhat-activation-key.yml

  tasks:

    - block:
      - name: Register with activationkey and consume subscriptions matching Red Hat Enterprise Linux Server
        redhat_subscription:
          state: present
          activationkey: "{{ rhactivationkey }}"
          org_id: "{{ rhorg_id }}"
          auto_attach: true
        become: yes

      - name: Remove existing Docker repositories from /etc/yum.repos.d/
        file:
          path: /etc/yum.repos.d/docker*.repo
          state: absent
        become: yes

      - name: Install required packages
        yum:
          name: "{{ packages }}"
          state: latest
        vars:
          packages:
            - yum-utils
            - device-mapper-persistent-data
            - lvm2
        become: yes

      - name: Add Docker repo
        get_url:
          url: https://download.docker.com/linux/centos/docker-ce.repo
          dest: /etc/yum.repos.d/docer-ce.repo
        become: yes

      # - name: Enable Docker Edge repo
      #   ini_file:
      #     dest: /etc/yum.repos.d/docer-ce.repo
      #     section: 'docker-ce-edge'
      #     option: enabled
      #     value: '0'
      #   become: yes
      #
      # - name: Enable Docker Test repo
      #   ini_file:
      #     dest: /etc/yum.repos.d/docer-ce.repo
      #     section: 'docker-ce-test'
      #     option: enabled
      #     value: '0'
      #   become: yes
      #
      # - name: Install containerd.io
      #   yum:
      #     name: containerd.io
      #     state: latest
      #   become: yes
      #
      # - name: Install Docker
      #   yum:
      #     name: "{{ packages }}"
      #     state: latest
      #   become: yes
      #   vars:
      #     packages:
      #       - docker-ce
      #       - docker-ce-cli
      #
      # - name: Start Docker service
      #   service:
      #     name: docker
      #     state: started
      #     enabled: yes
      #   become: yes
      # when: ec2_tag_group == "webserver"
