---
- name: Add Database to MySQL
  hosts: ec2
  gather_facts: no
  vars_files:
    - ./vars/mysql-vars.yml

  tasks:


    - mysql_user:
        name: mford
        state: present
        login_host: localhost
        login_user: root
        login_password: redhat123
        password: redhat123
        priv: "*.*:ALL"

    
