---
- name: Provision MySQL
  hosts: ec2
  become: yes
  vars_files:
    - ./vars/mysql-vars.yml

  tasks:

    - name: Install pip
      easy_install:
        name: pip
        state: latest

    - name: Install PyMySQL python module
      pip:
        name: PyMySQL

    - name: Call MySQL Installation Role
      include_role:
        name: unxnn.mysql
