---
- name: Provision AWS Instances
  hosts: localhost
  gather_facts: no
  vars_files:
    - ./vars/default-vars.yml
    - ./credentials/tower_creds.yml

  tasks:

    - name: Set Machine Type to Micro
      set_fact:
        machine_type: t2.micro
        ec2_root_volume_name: /dev/xvda
      when: instance_size == "micro"

    - name: Set Machine Type to Small
      set_fact:
        machine_type: t3.small
        ec2_root_volume_name: /dev/sda1
      when: instance_size == "small"

    - name: Set Machine Type to Medium
      set_fact:
        machine_type: t3.medium
        ec2_root_volume_name: /dev/sda1
      when: instance_size == "medium"

    - name: Set Machine Type to large
      set_fact:
        machine_type: t3.large
        ec2_root_volume_name: /dev/sda1
      when: instance_size == "large"

    - name: Create AWS SSH Key Pair
      ec2_key:
        region: "{{ ec2_region }}"
        name: "{{ ec2_prefix }}-key"
      register: create_key

    # This is just saving off the private key, this can only be done 1 time on the first creation of the key, pair
    - name: Save Private Key Locally
      copy:
        content: "{{ create_key.key.private_key }}"
        dest: "{{ working_dir }}/{{ ec2_prefix }}-key-private.pem"
        mode: '0400'
      when: create_key.changed
      no_log: yes

    - name: Save Public Key Locally
      copy:
        content: "{{ create_key.key.public_key }}"
        dest: "{{ working_dir }}/{{ ec2_prefix }}-key.pub"
        mode: '0400'
      when: create_key.changed
      no_log: yes

    # - name: Set Key information to string
    #   set_fact:
    #     private_key_content: lookup('file', '{{ working_dir }}/{{ ec2_prefix }}-key-private.pem')

    - name: Update Ansible Tower AWS SSH Credential
      tower_credential:
        name: AWS Demo Instances Key
        organization: Default
        tower_host: "{{ tower_url }}"
        tower_username: "{{ tower_user }}"
        tower_password: "{{ tower_pass }}"
        kind: ssh
        username: "{{ instance_username }}"
        # ssh_key_data: "{{ working_dir }}/{{ ec2_prefix }}-key-private.pem"
        ssh_key_data: "{{ lookup('file', '{{ working_dir }}/{{ ec2_prefix }}-key-private.pem') }}"
        tower_verify_ssl: false
      delegate_to: localhost
      run_once: true
      when: create_key.changed

    # - name: delete flat-file private key
    #   file:
    #     path: "{{ working_dir }}/{{ ec2_prefix }}-key-private.pem"
    #     state: absent

    - name: Gather Subnet Information
      ec2_vpc_subnet_info:
        region: "{{ ec2_region }}"
        filters:
          "tag:application": "{{ application }}"
          "tag:provisioner": "mford"
      register: subnet_info

    # - debug:
    #     var: subnet_info

    - name: "Create EC2 instances for {{ application }}"
      ec2:
        assign_public_ip: true
        key_name: "{{ ec2_prefix }}-key"
        group: "{{ ec2_prefix }}-sg"
        instance_type: "{{ machine_type }}"
        image: "{{ ec2_image_id }}"
        region: "{{ ec2_region }}"
        count: "{{ num_instances }}"
        wait: "{{ ec2_wait }}"
        vpc_subnet_id: "{{ subnet_info.subnets[0].id }}"
        instance_tags:
          provisioner: mford
          application: "{{ application }}"
          Name: "{{ application }}-server"
          demo: appdeployment
        volumes:
          - device_name: "{{ ec2_root_volume_name }}"
            volume_type: gp2
            volume_size: "{{ ec2_root_volume_size }}"
            delete_on_termination: true

    - pause:
        seconds: 60
