---
- name: Ensure Standard RHEL8 Configuration
  hosts: ec2
  gather_facts: yes
  vars_files:
    - ./credentials/redhat-activation-key.yml

  tasks:

    - block:
      - name: Register with activationkey and consume subscriptions matching Red Hat Enterprise Linux Server
        redhat_subscription:
          state: present
          activationkey: "{{ rhactivationkey }}"
          org_id: "{{ rhorg_id }}"
          auto_attach: true
        become: yes

      - name: upgrade all packages
        yum:
          name: '*'
          state: latest
          disablerepo: rhel-7-server-htb-rpms
        become: yes

      - name: Install Apache
        yum:
          name: httpd
          state: latest
        become: yes

      - name: build report
        include_role:
          name: build_report
      when: ec2_tag_group == "rhel"
