---
- name: Provision MySQL
  hosts: ec2
  vars_files:
    - ./vars/mysql-vars.yml
    - ./credentials/snow_creds.yml

  tasks:

    - name: Install pip
      easy_install:
        name: pip
        state: latest
      become: yes

    - name: Install PyMySQL python module
      pip:
        name: PyMySQL


    - name: Call MySQL Installation Role
      include_role:
        name: unxnn.mysql

    - name: Create an incident
      snow_record:
        username: "{{ SNOW_USERNAME }}"
        password: "{{ SNOW_PASSWORD }}"
        instance: "{{ SNOW_INSTANCE }}"
        state: present
        data:
          short_description: "{{ application }} deployed to AWS instances."
          severity: 3
          priority: 2
      register: new_incident
      delegate_to: localhost
      run_once: yes
