---
- name: Ensure docker python package is installed
  hosts: localhost
  gather_facts: no
  # vars_files:
  #   - ./vars/default-vars.yml

  tasks:
    - name: Ensure docker python package is installed
      pip:
        name: docker
        umask: 0022
        state: forcereinstall


- name: Ensure vault is running
  hosts: ec2
  gather_facts: no
  vars_files:
    - ./vars/default-vars.yml

  tasks:

    - block:

      - name: Create vault container
        docker_container:
          name: vault
          image: vault
          env:
            VAULT_DEV_ROOT_TOKEN_ID: ansible
          published_ports:
            - 8200:8200
      when: ec2_tag_group == "webserver"
