---
- name: Ensure vault is running
  hosts: ec2
  gather_facts: no
  vars_files:
    - ./vars/default-vars.yml
    - ./credentials/redhat-activation-key.yml

  tasks:

    - block:
      - name: Ensure docker python package is installed
        pip:
          name: docker
          umask: 0022
          state: forcereinstall
          
      - name: Create vault container
        docker_container:
          name: vault
          image: vault
          env:
            VAULT_DEV_ROOT_TOKEN_ID: ansible
          published_ports:
            - 8200:8200
      when: ec2_tag_group == "webserver"
