---
- name: Set password for login
  hosts: ec2
  become: yes
  vars_files:
    - ./vars/mysql-vars.yml

  tasks:

    - name: Create a password for the user
      user:
        name: centos
        password: thepassword
