---
- name: Provision AWS infrastructure via Terraform
  hosts: localhost
  gather_facts: no

  tasks:

    - name: Clone Terraform repo to server
      git:
        repo: https://github.com/michaelford85/aws-terraform.git
        dest: /tmp/aws-terraform


    - command:
        cmd: terraform init
        chdir: /tmp/aws-terraform

    - terraform:
        project_path: /tmp/aws-terraform
        state: present
      register: terraform_output

    - debug:
        var: terraform_output
