---
- name: Provision AWS infrastructure via Terraform
  hosts: localhost
  gather_facts: no

  tasks:


    - command:
        cmd: terraform init
        chdir: /tmp/aws-terraform

    - terraform:
        project_path: /tmp/aws-terraform
        state: present
      register: terraform_output

    - debug:
        var: terraform_output
