---
- name: Populate Tower Resources from AWS
  hosts: localhost
  gather_facts: no

  tasks:

    - terraform:
        project_path: /tmp/aws-terraform
        state: absent
      register: terraform_output

    - debug:
        var: terraform_output
      tags:
        - debug
