---
- name: "Create GCP Kubernetes Cluster {{ gcp_prefix }}-cluster"
  gcp_container_cluster:
    name: "{{ gcp_prefix }}-cluster"
    # initial_node_count: 3
    master_auth:
      username: admin
      password: gwC3aS25ztYsN9U*Y8
    node_config:
      machine_type: n1-standard-1
      disk_size_gb: 100
    location: "{{ gcp_zone }}"
    state: present
  register: gcp_cluster

- name: create a node pool
  gcp_container_node_pool:
    name: "{{ gcp_prefix }}-pool"
    initial_node_count: 3
    cluster: "{{ gcp_cluster }}"
    location: "{{ gcp_zone }}"
    state: present
