---
- name: "Create GCP Kubernetes Cluster {{ gcp_prefix }}-cluster"
  gcp_container_cluster:
    name: "{{ gcp_prefix }}-cluster"
    initial_node_count: 2
    master_auth:
      username: cluster_admin
      password: my-secret-password
    node_config:
      machine_type: n1-standard-1
      disk_size_gb: 50
    location: "{{ gcp_zone }}"
    state: present
  register: gcp_cluster
